### PR TITLE
Update dynamic_info.h for 16.3.1 iPhone Pro Max

### PR DESCRIPTION
**Pull request by CybrCyko**
for iProMax 13

### CODE REVIEW

**Comment by 34306** [comment]
wrong offsets.
._vm_map__hdr__links__prev
._vm_map__hdr__links__next
._vm_map__hdr__links__start
._vm_map__hdr__links__end

All 4 of these are need + 0x10 not 0x8

**Comment by CybrCyko** [comment]
Updated them.

**Comment by 34306** [comment]
> Updated them.

Still wrong. It need added, not remove

**Comment by CybrCyko** [comment]
think i fixed it

**Pull request merged**
